### PR TITLE
srccon and nicar blog post

### PR DESCRIPTION
**Pull request by kissane**
To stage at earliest convenience—should go live Wednesday morning, early.

### CODE REVIEW

**Comment by sinker** [comment]
@kissane on your local version can you confirm that the SRCCON blog post is still a valid post?

**Comment by sinker** [comment]
I raise this because based on the PR alone, it looks like it deletes that post. But maybe I'm just not looking at the diffs right.

**Comment by kissane** [comment]
Yeah, SRCCON post is fine

**Comment by sinker** [comment]
OK Great!

**Pull request merged**
